name: shop
description: A new Flutter project.
version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  dio: ^2.1.7
  flutter_swiper: ^1.1.6
  flutter_screenutil: ^0.5.2
  url_launcher: ^5.0.3
  flutter_easyrefresh: ^1.2.7
  provide: ^1.0.2
  fluttertoast: ^3.1.0
  fluro: ^1.4.0
  flutter_html: ^0.10.1
  sqflite: ^1.1.5
  shared_preferences: ^0.5.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
